from pva_tsdb_connector.enums import MetricCategories, MetricUnits, MetricDefaultOrders
from pva_tsdb_connector.models import MetricModel


METRIC_MODELS = [
    MetricModel(
        uid=1,
        name="Time Since All Time High",
        description="How much time has passed since the all time high.",
        category=MetricCategories.EXTREME_VALUES,
        unit=MetricUnits.SECONDS,
        default_order=MetricDefaultOrders.ASC,
    ),
    MetricModel(
        uid=2,
        name="Time Since All Time Low",
        description="How much time has passed since the all time low.",
        category=MetricCategories.EXTREME_VALUES,
        unit=MetricUnits.SECONDS,
        default_order=MetricDefaultOrders.ASC,
    ),
    MetricModel(
        uid=3,
        name="Rate of Change from All Time High",
        description="How the latest value compares to the all time high.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.ASC,
    ),
    MetricModel(
        uid=4,
        name="Rate of Change from All Time Low",
        description="How the latest value compares to the all time low.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.ASC,
    ),
    # Changes from 1 week, 1 month, 6 months etc prior to last measurement
    MetricModel(
        uid=5,
        name="Rate of Change from 1 Week Prior",
        description="How the latest value compares to the value 1 week before.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=6,
        name="Rate of Change from 1 Month Prior",
        description="How the latest value compares to the value from 1 month before.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=7,
        name="Rate of Change from 6 Months Prior",
        description="How the latest value compares to the value from 6 months before.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=8,
        name="Rate of Change from 1 Year Prior",
        description="How the latest value compares to the value from 1 year before.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=9,
        name="Rate of Change from 10 Years Prior",
        description="How the latest value compares to the value from 10 years before.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    # Changes in the last week, month, year etc
    MetricModel(
        uid=10,
        name="Rate of Change This Week",
        description="How the latest value has changed since this week began.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=11,
        name="Rate of Change This Month",
        description="How the latest value has changed since this month began.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=12,
        name="Rate of Change This Year",
        description="How the latest value has changed since this year began.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=13,
        name="Rate of Change This Decade",
        description="How the latest value has changed since this decade began.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=14,
        name="Rate of Change This Century",
        description="How the latest value has changed since this century began.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
    MetricModel(
        uid=15,
        name="Rate of Change From Previous Value",
        description="How the latest value has changed since the previous measurement.",
        category=MetricCategories.CHANGE_RATE,
        unit=MetricUnits.PROPORTION,
        default_order=MetricDefaultOrders.DESC,
    ),
]
